services:
  # Redpanda service
  binance-redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.11
    container_name: binance-redpanda
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "1"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://binance-redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://binance-redpanda:28082,OUTSIDE://localhost:8082
      - --rpc-addr
      - 0.0.0.0:33145
      - --advertise-rpc-addr
      - binance-redpanda:33145
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 9644:9644
      - 28082:28082
      - 29092:29092
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s

  # Redpanda Console for UI
  binance-redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.4.6
    container_name: binance-redpanda-console
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["binance-redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://binance-redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://binance-redpanda:9644"]
        connect:
          enabled: false
    ports:
      - 1003:8080
    depends_on:
      binance-redpanda:
        condition: service_healthy

  # binanceProducer service
  binance-producer:
    build:
      context: ./binanceProducer
      dockerfile: Dockerfile
    container_name: binance-producer
    environment:
      REDPANDA_BROKERS: "binance-redpanda:29092"
      ASSET_PRICES_TOPIC: "data.asset_prices"
    depends_on:
      binance-redpanda:
        condition: service_healthy

  # binanceConsumer service
  binance-consumer:
    build:
      context: ./binanceConsumer
      dockerfile: Dockerfile
    container_name: binance-consumer
    ports:
      - 9090:8080
      - 7014:7077
      - 4010:4040
    environment:
      SPARK_MASTER: "local[*]"
      REDPANDA_BROKERS: "binance-redpanda:29092"
      ASSET_PRICES_TOPIC: "data.asset_prices"
      ASSET_SCHEMA_LOCATION: "/src/schemas/assets.avsc"
      ASSET_CASSANDRA_HOST: "binance-cassandra"
      ASSET_CASSANDRA_PORT: 9042
      ASSET_CASSANDRA_USERNAME: "adminadmin"
      ASSET_CASSANDRA_PASSWORD: "adminadmin"
      ASSET_CASSANDRA_KEYSPACE: 'assets'
      ASSET_CASSANDRA_TABLE: 'assets'
    depends_on:
      binance-redpanda:
        condition: service_healthy
      binance-cassandra:
        condition: service_healthy
      binance-cassandra-init:
        condition: service_completed_successfully

  binance-consumer-worker-1:
    build:
      context: ./binanceConsumer
      dockerfile: SparkWorker.DockerFile
    container_name: binance-consumer-worker-1
    ports:
      - 8041:8081
    depends_on:
      - binance-consumer
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://binance-consumer:7077

  binance-consumer-worker-2:
    build:
      context: ./binanceConsumer
      dockerfile: SparkWorker.DockerFile
    container_name: binance-consumer-worker-2
    ports:
      - 8042:8081
    depends_on:
      - binance-consumer
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://binance-consumer:7077

  # ML Model Service
  binance-model-service:
    build:
      context: ./MLPipeline
      dockerfile: Dockerfile
    container_name: binance-model-service
    environment:
      SPARK_MASTER: "local[*]"
      REDPANDA_BROKERS: "binance-redpanda:29092"
      ASSET_PRICES_TOPIC: "data.asset_prices"
      ASSET_CASSANDRA_HOST: "binance-cassandra"
      ASSET_CASSANDRA_PORT: 9042
      ASSET_CASSANDRA_USERNAME: "adminadmin"
      ASSET_CASSANDRA_PASSWORD: "adminadmin"
      ASSET_CASSANDRA_KEYSPACE: 'assets'
      ASSET_CASSANDRA_TABLE: 'assets'
      MODEL_PREDICTIONS_TABLE: 'model_predictions'
      MODEL_SERVICE_STREAM_MODE: 'true'
      MODELS_DIR: '/app/trained_models'
    volumes:
      - ./MLPipeline/trained_models:/app/trained_models
    depends_on:
      binance-redpanda:
        condition: service_healthy
      binance-cassandra:
        condition: service_healthy
      binance-consumer:
        condition: service_started

  # Cassandra service
  binance-cassandra:
    image: cassandra:4.1.3
    container_name: binance-cassandra
    ports:
      - 9042:9042
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Cassandra initialization service
  binance-cassandra-init:
    image: cassandra:4.1.3
    container_name: binance-cassandra-init
    depends_on:
      binance-cassandra:
        condition: service_healthy
    volumes:
      - ./init-cassandra.sh:/init-cassandra.sh
      - ./Cassandra/init-model-predictions.cql:/init-model-predictions.cql
    command: ["/init-cassandra.sh"]

  binance-grafana:
    image: grafana/grafana-enterprise
    container_name: binance-grafana
    depends_on:
      binance-cassandra:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-log:/var/log/grafana
      - grafana-config:/etc/grafana

volumes:
  grafana-data: {}
  grafana-log: {}
  grafana-config: {} 