version: "3.6"
services:
  binance-producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance-producer
    environment:
      REDPANDA_BROKERS: "binance-redpanda:29092"
      ASSET_PRICES_TOPIC: "data.asset_prices"
    depends_on:
      binance-redpanda:
        condition: service_healthy