{
 "title": "Crypto Assets Dashboard",
 "tags": [
  "crypto",
  "binance"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cryptocurrency Prices",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "keyspace": "assets",
     "target": "SELECT asset_name, asset_price, toUnixTimestamp(collected_at)*1000 as time_ms FROM assets"
    }
   ]
  },
  {
   "title": "Latest Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyspace": "assets",
     "target": "SELECT asset_name, asset_price FROM assets LIMIT 10"
    }
   ]
  },
  {
   "title": "Asset Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "keyspace": "assets",
     "target": "SELECT asset_name, asset_price FROM assets"
    }
   ]
  }
 ]
}