apiVersion: 1

datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource
    access: proxy
    orgId: 1
    isDefault: true
    version: 1
    editable: true
    jsonData:
      keyspace: assets
      username: adminadmin
      port: 9042
      host: binance-cassandra
    secureJsonData:
      password: adminadmin 